### numpy 모튤
- random 모듈을 이용한 난수 발생
- random.randint(시작값, 종료값):시작~종료값 범위에 있는 정수를 임의로 발생

In [1]:
import numpy as np

np.random.randint(10, 20) #종료값은 포함되지 않음 (10~19)



17

### 0~50 사이의 숫자를 무작위로 생성
- 10개의 데이터 생성
- 생성된 숫자는 리스트형 데이터로 저장
- for문 사용

In [2]:
import numpy as np

rd_lst=[]

for i in range(10):
    num=np.random.randint(0, 51)
    rd_lst.append(num)

print(rd_lst)

[22, 16, 48, 42, 16, 28, 9, 44, 42, 6]


In [3]:
import numpy as np

rd_lst=[]

for i in range(10):
    rd_lst.append(np.random.randint(0, 51))

print(rd_lst)

[20, 19, 42, 27, 43, 23, 18, 26, 47, 18]


In [4]:
rd_lst=[np.random.randint(0, 51) for i in range(10)]
print(rd_lst)

[38, 32, 22, 8, 25, 18, 33, 23, 19, 24]


- words 데이터에서 글자수가 4개 이상인 데이터를 찾아 new_words 에 리스트로 저장

In [5]:
words = ["멀티캠퍼스","티스토리", "블로그", "파이썬", "for", "프로그래밍", "반복"]
new_words = []


for word in words:
    if len(word)>3:
        new_words.append(word)

print(new_words)
    

['멀티캠퍼스', '티스토리', '프로그래밍']


In [6]:
#[추가할 데이터 for문 if 문]
new_words=[word for word in words if len(word)>3]
print(new_words)

['멀티캠퍼스', '티스토리', '프로그래밍']


In [7]:
words = [ [ "이중 for문", "파이썬", "프로그래밍", "스터디" ], 
        [ "Python", "NLP", "ML", "DL" ],
        [ "leetCode", "BaekJoon", "HackerRank" ], 
        [ "멀티캠퍼스", "COMPAS", "DACON", "Kaggle" ] ]

In [8]:
# word가 가지고 있는 단어의 길이가 4 이상인 데이터만 출력
for word_lst in words: 
    print(word_lst)
    for word in word_lst:
        print(word)

['이중 for문', '파이썬', '프로그래밍', '스터디']
이중 for문
파이썬
프로그래밍
스터디
['Python', 'NLP', 'ML', 'DL']
Python
NLP
ML
DL
['leetCode', 'BaekJoon', 'HackerRank']
leetCode
BaekJoon
HackerRank
['멀티캠퍼스', 'COMPAS', 'DACON', 'Kaggle']
멀티캠퍼스
COMPAS
DACON
Kaggle


In [9]:
words = [ [ "이중 for문", "파이썬", "프로그래밍", "스터디" ], 
        [ "Python", "NLP", "ML", "DL" ],
        [ "leetCode", "BaekJoon", "HackerRank" ], 
        [ "멀티캠퍼스", "COMPAS", "DACON", "Kaggle" ] ]
# word가 가지고 있는 단어의 길이가 4 이상인 데이터만 new_words에 리스트로 추가
new_words=[]

for word_lst in words: 
    for word in word_lst:
          if len(word)>=4:
                new_words.append(word)
print(new_words)

['이중 for문', '프로그래밍', 'Python', 'leetCode', 'BaekJoon', 'HackerRank', '멀티캠퍼스', 'COMPAS', 'DACON', 'Kaggle']


In [10]:
new_words=[word for word_lst in words for word in word_lst if len(word)>=4]
print(new_words)

['이중 for문', '프로그래밍', 'Python', 'leetCode', 'BaekJoon', 'HackerRank', '멀티캠퍼스', 'COMPAS', 'DACON', 'Kaggle']


### random 모듈을 이용한 리스트 값 발생
- 기준:0~50 사이의 난수 발생
- 1세트당 인수가(값) 10~20 사이의 값응ㄹ 갖는다.
- 전체 세트:5세트 생성
- 예)[[0,24,13],[3,18,15], ......]

In [11]:
import numpy as np

In [12]:
print(np.random.randint(51)) #0~50 사이의 정수형1개 발생
print(np.random.randint(25,51)) #25~50 사이의 난수 발생
print(np.random.randint(0, 51, 10)) #0~50 사이의 난수 10개 발생
print(np.random.randint(51, size=10)) #0~50 사이의 난수 10개 발생
print(np.random.randint(0, 51, size=10)) #0~50 사이의 난수 10개 발생  

34
40
[42 48 30 42 29 11 26 27 27 20]
[30  9 37 42 27 24 18 31 30 10]
[36 11 40 24 12  2 49 24 41 29]


## 요구사항: 리스트 개체를 생성하는 코드를 작성해주세요
- 리스트 개체는 총 5개의 리스트 요소를 가지고 있고 각 리스트 요소마다 10에서 20개 사의 값을 가지고 있습니다.
- 이 값은 0 ~ 50 사이의 임의의 값으로 만들어져 있습니다.
- [[0, 24, 3, ..20], [44, 14, 8, ..10], [0, 3, 12, ..13], [49, 24, 13, ..15], [0, 24, 3, ..17]]
### 문제 해결 알고리즘
- 10~20 size 발생: random.randint(10, 21) ==> size
- 0~50 사이값 발생: random.randint(0, 51, size=10-20)
- 리스트 인수 5개 생성: for i range(5)


In [13]:
lst_a=[]


for i in range(5):
    lst_a.append(np.random.randint(51,size=np.random.randint(10,21)))

print(lst_a)

[array([18, 32, 24, 36,  8, 39, 35, 30, 40, 47, 46, 43]), array([43, 23, 16, 31, 11, 25, 16, 28, 13, 45, 27, 20, 48, 40]), array([32, 19, 40, 39,  8, 30,  0, 14,  7, 39, 38, 12, 50, 18, 42]), array([26, 42, 49, 26, 30, 20, 17,  1, 50, 40, 44, 26, 18, 43, 17, 25, 21,
       21,  1, 39]), array([ 1, 23,  0, 26, 22, 23, 35, 34,  2, 32, 43, 44,  6, 50, 23, 28, 46,
       48, 18, 12])]


In [14]:
lst_a=[list(np.random.randint(51,size=np.random.randint(10,21))) for i in range(5)]
print(lst_a)

[[5, 17, 20, 4, 30, 11, 6, 22, 43, 23, 25, 50, 39, 27, 31, 44, 9, 38, 3, 11], [28, 32, 37, 14, 25, 39, 5, 24, 8, 43, 47, 25, 21, 49, 26, 38, 39, 22, 13], [35, 41, 37, 0, 49, 13, 48, 16, 17, 49, 3, 11, 10, 28, 48, 29, 6, 25, 13], [15, 43, 28, 26, 6, 26, 39, 27, 43, 22, 5, 31, 27, 44, 6, 25, 35, 24], [19, 43, 41, 49, 48, 29, 47, 44, 19, 1, 30, 28, 39, 45, 48, 36, 1, 12, 43, 24]]


### [요구사항] 입력된 숫자 데이터에서 최대값/최소값/합계 계산
- 1. data에 입력된 값을 기준으로 계산
- 2. 위에서 생성된 rd_lst 데이터를 이용해 계산

#### 제한조건
- sum(), max(), min() 함수 사용 금지

In [15]:
data=[34, 23, 20, 43, 1, 5, 2, 14, 18, 24, 40, 18, 38, 4, 3, 22, 43, 6, 36, 13]

tmpMax=data[0]
tmpMin=data[0]
tmpSum=0

for dt in data:
    # 최대값
    if dt>tmpMax:
        tmpMax=dt
    #최소값
    if dt<tmpMin:
        tmpMin=dt
    #합계
    tmpSum+=dt

print(f'최대값:{tmpMax}, 최소값: {tmpMin} , 합계: {tmpSum}')

최대값:43, 최소값: 1 , 합계: 407


In [16]:
lst_a=[list(np.random.randint(51,size=np.random.randint(10,21))) for i in range(5)]
print(lst_a)

[[31, 44, 2, 19, 39, 40, 25, 37, 6, 7, 16, 23, 35, 33, 50, 49, 36, 36, 5], [47, 14, 29, 36, 17, 39, 40, 12, 28, 41, 16, 49], [5, 26, 7, 42, 0, 48, 41, 46, 36, 43, 50, 9, 38], [32, 20, 33, 25, 5, 10, 15, 13, 44, 46, 28, 39, 21, 1], [26, 3, 20, 10, 25, 47, 14, 33, 26, 31, 35, 8, 10, 47, 25]]


In [24]:
lst_a=[[43, 46, 42, 14, 11, 5, 25, 49, 37, 12, 0, 0, 2, 16, 42, 6], [0, 43, 48, 32, 46, 4, 40, 3, 31, 14, 34, 38, 4, 41, 15, 30], [17, 8, 7, 49, 35, 44, 0, 43, 40, 20, 36, 36, 41, 3], [34, 11, 18, 9, 32, 11, 38, 35, 18, 48, 46, 27, 12, 17, 32, 24, 21, 43], [2, 43, 32, 47, 33, 42, 20, 11, 40, 32, 26, 18, 29, 28, 6]]

tmpMax=lst_a[0][0]
tmpMin=lst_a[0][0]
tmpSum=0

for i in lst_a:
    for list_a in i:
    #최대값
        if list_a>tmpMax:
            tmpMax=list_a
    #최소값
        if list_a<tmpMin:
            tmpMin=list_a
    #합계
        tmpSum+=list_a

print(f'최대값:{tmpMax}, 최소값: {tmpMin} , 합계: {tmpSum}')


최대값:49, 최소값: 0 , 합계: 2037


In [46]:
lst_a=[[43, 46, 42, 14, 11, 5, 25, 49, 37, 12, 0, 0, 2, 16, 42, 6], [0, 43, 48, 32, 46, 4, 40, 3, 31, 14, 34, 38, 4, 41, 15, 30], [17, 8, 7, 49, 35, 44, 0, 43, 40, 20, 36, 36, 41, 3], [34, 11, 18, 9, 32, 11, 38, 35, 18, 48, 46, 27, 12, 17, 32, 24, 21, 43], [2, 43, 32, 47, 33, 42, 20, 11, 40, 32, 26, 18, 29, 28, 6]]

tmp_lst=[0, lst_a[0][0], lst_a[0][0]]

for i in lst_a:
    for list_a in i:
    #최대값
        if list_a>tmpMax:
            tmpMax=list_a
    #최소값
        if list_a<tmpMin:
            tmpMin=list_a
    #합계
        tmpSum+=tmp_lst

print(f'최대값:{tmpMax}, 최소값: {tmpMin} , 합계: {tmpSum}')


TypeError: unsupported operand type(s) for +=: 'int' and 'list'

### 각 그룹별 계산
- 그룹단위 최대/최소/합계
- 전체 최대값/최소값/합계

In [58]:
lst_a=[list(np.random.randint(51,size=np.random.randint(10,21))) for i in range(5)]
print(lst_a)

[[47, 40, 17, 18, 17, 18, 11, 26, 7, 2, 14, 5, 39, 11, 31, 30, 19], [24, 35, 7, 22, 7, 45, 13, 25, 37, 10, 34, 26, 22, 0], [48, 8, 13, 18, 31, 13, 40, 17, 33, 50], [28, 4, 18, 49, 31, 34, 2, 35, 26, 32, 42, 10, 43, 29, 19, 25, 16], [26, 16, 27, 24, 42, 48, 41, 2, 19, 17]]


In [59]:
T_lst=[0, lst_a[0][0], lst_a[0][0]] #전체 값 계산
G_lst=[]#그룹별 최대값/최소값/합계를 저장할 리스트(출력)

for lst in lst_a:
    tmp_lst=[0, lst[0], lst[0]] # 그룹별 계산 리스트 변수
    for dt in lst:
        if dt>tmp_lst[1]: #최대값 찾기
            tmp_lst[1]=dt
        if dt<tmp_lst[2]: #최소값 찾기
            tmp_lst[2]=dt
        tmp_lst[0]+=dt #합계
    G_lst.append(tmp_lst) # 그룹별 계산 결과 리스트에 추가
    
    # 전체 데이터 누적합계 및 최대값/최소값 찾기
    T_lst[0]=T_lst[0]+tmp_lst[0] # 전체 누적합계
    
    if tmp_lst[1]>T_lst[1]:
        T_lst[1]=tmp_lst[1]
    if tmp_lst[2]<T_lst[2]:
        T_lst[2]=tmp_lst[2]
    
print('그룹별\n', G_lst, '\n')
print('전체데이터', T_lst)


그룹별
 [[352, 47, 2], [307, 45, 0], [271, 50, 8], [443, 49, 2], [262, 48, 2]] 

전체데이터 [1635, 50, 0]
